language: java
jdk: 
 - openjdk8

env:
  global:
    - CC_TEST_REPORTER_ID=0436ad9c80bd586bc95a0392d2f98ed3e362db3734e0eac2fac8db4c4d5117db
    
before_install:
 - cd ProtoBot
 - pwd
 - ls -la
 - chmod +x gradlew
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

script:
 - ./gradlew build
 - ./gradlew jacocoTestReport

after_script:
 - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage build/customJacocoReportDir/test/jacocoTestReport.xml --input-type jacoco
 - ./cc-test-reporter format-coverage --prefix /ProtoBot
 - ./cc-test-reporter upload-coverage 
